name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.RootPassword }}
          MYSQL_DATABASE: my_database
          mysql user: ${{ secrets.DatabaseId }}
          mysql password: ${{ secrets.DatabasePassword }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: make connection-config.properties
        run: |
          mkdir -p ./src/main/resources/config && \
          echo "${{ secrets.CONNECTION }}" > ./src/main/resources/config/connection-config.properties
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # - name: Build with Gradle
      #   run: ./gradlew build
      - name: gradlew 권한부여
        run: chmod +x gradlew
      - name: wrap Gradle
        run: gradle wrapper
      - name: Build With Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
