name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DatabasePassword }}
          MYSQL_DATABASE: cjadb
          MYSQL_USER: ${{ secrets.DatabaseId }}
          MYSQL_PASSWORD: ${{ secrets.DatabasePassword }}
        options: >-
          --health-cmd="mysqladmin ping -h localhost --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: make connection-config.properties
      run: |
        mkdir -p ./src/main/resources/config && \
        echo "${{ secrets.CONNECTION }}" > ./src/main/resources/config/connection-config.properties
    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h mysql --silent; then
            echo "MySQL is up!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 5
        done
    - name: wrap Gradle
      run: gradle wrapper
    - name: Build With Gradle
      run: ./gradlew build

    - name: Run tests
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.DatabasePassword }} # 루트 비밀번호
        MYSQL_DATABASE: test_db # 생성할 데이터베이스 이름
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cjadb
        SPRING_DATASOURCE_USERNAME: ${{ secrets.DatabaseId }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.DatabasePassword }}
      run: ./gradlew test
